; 투덜이 스머프 IT 홀딩스 - NMS Core v1.0 구성 파일

[GLOBAL]
log_level = INFO

[SNMP_TRAP]
; 키 중복 방지를 위해 trap_ 접두어 사용
trap_enabled = true
trap_port = 1162

[SYSLOG]
; 키 중복 방지를 위해 syslog_ 접두어 사용
syslog_enabled = true
syslog_port = 1514

[DATABASE]
db_host = 127.0.0.1
db_name = nms_core
db_user = toos_admin
db_pass = xxxuu111
db_port = 33306
db_charset = utf8mb4
